/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace HalalChain {
      
    export type BatchStruct = {producer: AddressLike, productName: string, ipfsCid: string, createdAt: BigNumberish, status: BigNumberish, auditor: AddressLike, auditedAt: BigNumberish, auditIpfsCid: string, rejectReason: string, parentBatchId: BigNumberish}

    export type BatchStructOutput = [producer: string, productName: string, ipfsCid: string, createdAt: bigint, status: bigint, auditor: string, auditedAt: bigint, auditIpfsCid: string, rejectReason: string, parentBatchId: bigint] & {producer: string, productName: string, ipfsCid: string, createdAt: bigint, status: bigint, auditor: string, auditedAt: bigint, auditIpfsCid: string, rejectReason: string, parentBatchId: bigint }
  
    }

  export interface HalalChainInterface extends Interface {
    getFunction(nameOrSignature: "AUDITOR_ROLE" | "DEFAULT_ADMIN_ROLE" | "PRODUCER_ROLE" | "getBatch" | "getRoleAdmin" | "grantRole" | "hasRole" | "nextBatchId" | "registerBatch" | "registerRevision" | "rejectBatch" | "renounceRole" | "revokeBatch" | "revokeRole" | "supportsInterface" | "verifyBatch"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BatchRegistered" | "BatchRejected" | "BatchRevoked" | "BatchVerified" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked"): EventFragment;

    encodeFunctionData(functionFragment: 'AUDITOR_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'PRODUCER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'getBatch', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'nextBatchId', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerBatch', values: [string, string]): string;
encodeFunctionData(functionFragment: 'registerRevision', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'rejectBatch', values: [BigNumberish, string, string]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeBatch', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'verifyBatch', values: [BigNumberish, string]): string;

    decodeFunctionResult(functionFragment: 'AUDITOR_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PRODUCER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextBatchId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerRevision', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rejectBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyBatch', data: BytesLike): Result;
  }

  
    export namespace BatchRegisteredEvent {
      export type InputTuple = [batchId: BigNumberish, producer: AddressLike, ipfsCid: string, parentBatchId: BigNumberish];
      export type OutputTuple = [batchId: bigint, producer: string, ipfsCid: string, parentBatchId: bigint];
      export interface OutputObject {batchId: bigint, producer: string, ipfsCid: string, parentBatchId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BatchRejectedEvent {
      export type InputTuple = [batchId: BigNumberish, auditor: AddressLike, reason: string, auditIpfsCid: string];
      export type OutputTuple = [batchId: bigint, auditor: string, reason: string, auditIpfsCid: string];
      export interface OutputObject {batchId: bigint, auditor: string, reason: string, auditIpfsCid: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BatchRevokedEvent {
      export type InputTuple = [batchId: BigNumberish, auditor: AddressLike, reason: string];
      export type OutputTuple = [batchId: bigint, auditor: string, reason: string];
      export interface OutputObject {batchId: bigint, auditor: string, reason: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BatchVerifiedEvent {
      export type InputTuple = [batchId: BigNumberish, auditor: AddressLike, auditIpfsCid: string];
      export type OutputTuple = [batchId: bigint, auditor: string, auditIpfsCid: string];
      export interface OutputObject {batchId: bigint, auditor: string, auditIpfsCid: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface HalalChain extends BaseContract {
    
    connect(runner?: ContractRunner | null): HalalChain;
    waitForDeployment(): Promise<this>;

    interface: HalalChainInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    AUDITOR_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    PRODUCER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getBatch: TypedContractMethod<
      [batchId: BigNumberish, ],
      [HalalChain.BatchStructOutput],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    nextBatchId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    registerBatch: TypedContractMethod<
      [productName: string, ipfsCid: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    registerRevision: TypedContractMethod<
      [parentBatchId: BigNumberish, ipfsCid: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    rejectBatch: TypedContractMethod<
      [batchId: BigNumberish, reason: string, auditIpfsCid: string, ],
      [void],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeBatch: TypedContractMethod<
      [batchId: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    verifyBatch: TypedContractMethod<
      [batchId: BigNumberish, auditIpfsCid: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'AUDITOR_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'PRODUCER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getBatch'): TypedContractMethod<
      [batchId: BigNumberish, ],
      [HalalChain.BatchStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'nextBatchId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'registerBatch'): TypedContractMethod<
      [productName: string, ipfsCid: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registerRevision'): TypedContractMethod<
      [parentBatchId: BigNumberish, ipfsCid: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rejectBatch'): TypedContractMethod<
      [batchId: BigNumberish, reason: string, auditIpfsCid: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeBatch'): TypedContractMethod<
      [batchId: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'verifyBatch'): TypedContractMethod<
      [batchId: BigNumberish, auditIpfsCid: string, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'BatchRegistered'): TypedContractEvent<BatchRegisteredEvent.InputTuple, BatchRegisteredEvent.OutputTuple, BatchRegisteredEvent.OutputObject>;
getEvent(key: 'BatchRejected'): TypedContractEvent<BatchRejectedEvent.InputTuple, BatchRejectedEvent.OutputTuple, BatchRejectedEvent.OutputObject>;
getEvent(key: 'BatchRevoked'): TypedContractEvent<BatchRevokedEvent.InputTuple, BatchRevokedEvent.OutputTuple, BatchRevokedEvent.OutputObject>;
getEvent(key: 'BatchVerified'): TypedContractEvent<BatchVerifiedEvent.InputTuple, BatchVerifiedEvent.OutputTuple, BatchVerifiedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;

    filters: {
      
      'BatchRegistered(uint256,address,string,uint256)': TypedContractEvent<BatchRegisteredEvent.InputTuple, BatchRegisteredEvent.OutputTuple, BatchRegisteredEvent.OutputObject>;
      BatchRegistered: TypedContractEvent<BatchRegisteredEvent.InputTuple, BatchRegisteredEvent.OutputTuple, BatchRegisteredEvent.OutputObject>;
    

      'BatchRejected(uint256,address,string,string)': TypedContractEvent<BatchRejectedEvent.InputTuple, BatchRejectedEvent.OutputTuple, BatchRejectedEvent.OutputObject>;
      BatchRejected: TypedContractEvent<BatchRejectedEvent.InputTuple, BatchRejectedEvent.OutputTuple, BatchRejectedEvent.OutputObject>;
    

      'BatchRevoked(uint256,address,string)': TypedContractEvent<BatchRevokedEvent.InputTuple, BatchRevokedEvent.OutputTuple, BatchRevokedEvent.OutputObject>;
      BatchRevoked: TypedContractEvent<BatchRevokedEvent.InputTuple, BatchRevokedEvent.OutputTuple, BatchRevokedEvent.OutputObject>;
    

      'BatchVerified(uint256,address,string)': TypedContractEvent<BatchVerifiedEvent.InputTuple, BatchVerifiedEvent.OutputTuple, BatchVerifiedEvent.OutputObject>;
      BatchVerified: TypedContractEvent<BatchVerifiedEvent.InputTuple, BatchVerifiedEvent.OutputTuple, BatchVerifiedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    
    };
  }