/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace HalalChain {
      
    export type BatchStruct = {producer: AddressLike, productName: string, ipfsCid: string, createdAt: BigNumberish, status: BigNumberish, auditor: AddressLike, auditedAt: BigNumberish, auditIpfsCid: string, rejectReason: string}

    export type BatchStructOutput = [producer: string, productName: string, ipfsCid: string, createdAt: bigint, status: bigint, auditor: string, auditedAt: bigint, auditIpfsCid: string, rejectReason: string] & {producer: string, productName: string, ipfsCid: string, createdAt: bigint, status: bigint, auditor: string, auditedAt: bigint, auditIpfsCid: string, rejectReason: string }
  
    }

  export interface HalalChainInterface extends Interface {
    getFunction(nameOrSignature: "getBatch" | "isAuditor" | "nextBatchId" | "owner" | "registerBatch" | "rejectBatch" | "setAuditor" | "verifyBatch"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AuditorSet" | "BatchRegistered" | "BatchRejected" | "BatchVerified"): EventFragment;

    encodeFunctionData(functionFragment: 'getBatch', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isAuditor', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'nextBatchId', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerBatch', values: [string, string]): string;
encodeFunctionData(functionFragment: 'rejectBatch', values: [BigNumberish, string, string]): string;
encodeFunctionData(functionFragment: 'setAuditor', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'verifyBatch', values: [BigNumberish, string]): string;

    decodeFunctionResult(functionFragment: 'getBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isAuditor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextBatchId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rejectBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAuditor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyBatch', data: BytesLike): Result;
  }

  
    export namespace AuditorSetEvent {
      export type InputTuple = [auditor: AddressLike, allowed: boolean];
      export type OutputTuple = [auditor: string, allowed: boolean];
      export interface OutputObject {auditor: string, allowed: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BatchRegisteredEvent {
      export type InputTuple = [batchId: BigNumberish, producer: AddressLike, ipfsCid: string];
      export type OutputTuple = [batchId: bigint, producer: string, ipfsCid: string];
      export interface OutputObject {batchId: bigint, producer: string, ipfsCid: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BatchRejectedEvent {
      export type InputTuple = [batchId: BigNumberish, auditor: AddressLike, reason: string, auditIpfsCid: string];
      export type OutputTuple = [batchId: bigint, auditor: string, reason: string, auditIpfsCid: string];
      export interface OutputObject {batchId: bigint, auditor: string, reason: string, auditIpfsCid: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BatchVerifiedEvent {
      export type InputTuple = [batchId: BigNumberish, auditor: AddressLike, auditIpfsCid: string];
      export type OutputTuple = [batchId: bigint, auditor: string, auditIpfsCid: string];
      export interface OutputObject {batchId: bigint, auditor: string, auditIpfsCid: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface HalalChain extends BaseContract {
    
    connect(runner?: ContractRunner | null): HalalChain;
    waitForDeployment(): Promise<this>;

    interface: HalalChainInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getBatch: TypedContractMethod<
      [batchId: BigNumberish, ],
      [HalalChain.BatchStructOutput],
      'view'
    >
    

    
    isAuditor: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    nextBatchId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    registerBatch: TypedContractMethod<
      [productName: string, ipfsCid: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    rejectBatch: TypedContractMethod<
      [batchId: BigNumberish, reason: string, auditIpfsCid: string, ],
      [void],
      'nonpayable'
    >
    

    
    setAuditor: TypedContractMethod<
      [auditor: AddressLike, allowed: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    verifyBatch: TypedContractMethod<
      [batchId: BigNumberish, auditIpfsCid: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getBatch'): TypedContractMethod<
      [batchId: BigNumberish, ],
      [HalalChain.BatchStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'isAuditor'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'nextBatchId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registerBatch'): TypedContractMethod<
      [productName: string, ipfsCid: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rejectBatch'): TypedContractMethod<
      [batchId: BigNumberish, reason: string, auditIpfsCid: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setAuditor'): TypedContractMethod<
      [auditor: AddressLike, allowed: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifyBatch'): TypedContractMethod<
      [batchId: BigNumberish, auditIpfsCid: string, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AuditorSet'): TypedContractEvent<AuditorSetEvent.InputTuple, AuditorSetEvent.OutputTuple, AuditorSetEvent.OutputObject>;
getEvent(key: 'BatchRegistered'): TypedContractEvent<BatchRegisteredEvent.InputTuple, BatchRegisteredEvent.OutputTuple, BatchRegisteredEvent.OutputObject>;
getEvent(key: 'BatchRejected'): TypedContractEvent<BatchRejectedEvent.InputTuple, BatchRejectedEvent.OutputTuple, BatchRejectedEvent.OutputObject>;
getEvent(key: 'BatchVerified'): TypedContractEvent<BatchVerifiedEvent.InputTuple, BatchVerifiedEvent.OutputTuple, BatchVerifiedEvent.OutputObject>;

    filters: {
      
      'AuditorSet(address,bool)': TypedContractEvent<AuditorSetEvent.InputTuple, AuditorSetEvent.OutputTuple, AuditorSetEvent.OutputObject>;
      AuditorSet: TypedContractEvent<AuditorSetEvent.InputTuple, AuditorSetEvent.OutputTuple, AuditorSetEvent.OutputObject>;
    

      'BatchRegistered(uint256,address,string)': TypedContractEvent<BatchRegisteredEvent.InputTuple, BatchRegisteredEvent.OutputTuple, BatchRegisteredEvent.OutputObject>;
      BatchRegistered: TypedContractEvent<BatchRegisteredEvent.InputTuple, BatchRegisteredEvent.OutputTuple, BatchRegisteredEvent.OutputObject>;
    

      'BatchRejected(uint256,address,string,string)': TypedContractEvent<BatchRejectedEvent.InputTuple, BatchRejectedEvent.OutputTuple, BatchRejectedEvent.OutputObject>;
      BatchRejected: TypedContractEvent<BatchRejectedEvent.InputTuple, BatchRejectedEvent.OutputTuple, BatchRejectedEvent.OutputObject>;
    

      'BatchVerified(uint256,address,string)': TypedContractEvent<BatchVerifiedEvent.InputTuple, BatchVerifiedEvent.OutputTuple, BatchVerifiedEvent.OutputObject>;
      BatchVerified: TypedContractEvent<BatchVerifiedEvent.InputTuple, BatchVerifiedEvent.OutputTuple, BatchVerifiedEvent.OutputObject>;
    
    };
  }