/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { HalalChain } from './HalalChain.js';
export * as factories from './factories/index.js';
export { HalalChain__factory } from './factories/HalalChain__factory.js';